LP1901895, updating carousels.adcoc
evergreen-library-system/Evergreen pull request #165
Opened 2022-04-06 17:23 UTC by gmontimantis

https://bugs.launchpad.net/evergreen/+bug/1901895

2022-04-21 00:59 UTC, sandbergja requested changes
Thanks, @gmontimantis! I had just one behavior that needs to be verified, then I'm happy to merge this.

2022-04-21 00:59 UTC, sandbergja commented on docs/modules/admin_initial_setup/pages/carousels.adoc
> +* *Recently Returned Items* - titles appear automatically based on the mostly recently circulated copy’s check-in scan date and time.  Shelving locations are not required to create this carousel.
I think shelving locations might be required for the "Recently returned" one to automatically update, based on the [config in the database](https://github.com/evergreen-library-system/Evergreen/blob/3663817ec8c975d09150fef4c578e1fbd7ae0312/Open-ILS/src/sql/Pg/upgrade/1175.schema.carousels.sql#L19) and the [perl script's handling of that config](https://github.com/evergreen-library-system/Evergreen/blob/518f9a2f7a383c0cff780bdf9fc33e7e90ffe5bc/Open-ILS/src/perlmods/lib/OpenILS/Application/Storage/Publisher/container.pm#L148-L151)

2022-08-17 15:07 UTC, gmontimantis commented
I edited the change!

2022-08-17 20:04 UTC, sandbergja commented
Thanks @gmontimantis !  Pushed to 3.8 and above

2022-08-17 20:04 UTC, closed without merging